version: '3.7'
services:
  jenkins:
    image: jenkinsci/blueocean
    volumes:
    - ./jenkins-data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_network




networks:
  jenkins_network:
    name: jenkins_network
#    driver: bridge
    ipam:
#      driver: default
      config:
        - subnet: 192.168.11.0/24
